// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Usuarios = __t.object("Usuarios", {
  nombre: __t.string(),
  correo: __t.string(),
  passwordHash: __t.string(),
  rol: __t.string(),
  activo: __t.bool(),
  creadoEn: __t.string(),
});
export type Usuarios = __Infer<typeof Usuarios>;

