// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string(),
  routeId: __t.string().name("route_id"),
  categoryLabel: __t.string().name("category_label"),
  name: __t.string(),
  subtitle: __t.string(),
  description: __t.string(),
  address: __t.string(),
  costStatus: __t.string().name("cost_status"),
  hours: __t.string(),
  audience: __t.string(),
  image: __t.string(),
  longitude: __t.string(),
  latitude: __t.string(),
  actualizadoEn: __t.string().name("actualizado_en"),
});
