// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CrearAdminInicialReducer from "../crear_admin_inicial_reducer";
import CrearUsuarioReducer from "../crear_usuario_reducer";

export type CrearAdminInicialParams = __Infer<typeof CrearAdminInicialReducer>;
export type CrearUsuarioParams = __Infer<typeof CrearUsuarioReducer>;

